#macro VIEW_WIDTH 640
#macro VIEW_HEIGHT 384
#macro VIEW_SCALE 2
#macro TARGET_FPS 60
#macro POINTS_PER_HEART 4
#macro K_LEFT 0
#macro K_RIGHT 1
#macro K_UP 2
#macro K_DOWN 3
#macro K_JUMP 4
#macro E_PRESS 7
#macro E_DOWN 8
#macro E_RELEASE 9
#macro BOMB_AOE_RADIUS 80
#macro RELEASE_MODE false
